---
- name: Update Linux hosts
  hosts: "{{ target_hosts | default('linux_servers') }}"
  become: yes
  tasks:
    - name: Hold linux-firmware on semaphore host (workaround mirror 500)
      command: apt-mark hold linux-firmware
      when: inventory_hostname == "ansible-semaphore"
      changed_when: false
      failed_when: false

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Unhold linux-firmware on semaphore host
      command: apt-mark unhold linux-firmware
      when: inventory_hostname == "ansible-semaphore"
      changed_when: false
      failed_when: false
