---
- name: Deploy BGInfo files to NETLOGON and create User Logon GPO (srv-work only)
  hosts: srv-work
  gather_facts: yes
  vars:
    domain_dns: work.local
    bginfo_dir: "C:\\Windows\\SYSVOL\\sysvol\\work.local\\scripts\\bginfo"
  tasks:

    - name: Ensure NETLOGON bginfo folder exists
      ansible.windows.win_file:
        path: "{{ bginfo_dir }}"
        state: directory

    - name: Download BGInfo.exe into NETLOGON bginfo
      ansible.windows.win_get_url:
        url: "https://www.dropbox.com/scl/fi/7di71bkr96osmuuy54sxl/Bginfo.exe?rlkey=kjxoykquz24rl9ihmkat02vvk&st=6ax9kmr3&dl=1"
        dest: "{{ bginfo_dir }}\\BGInfo.exe"
        force: yes

    - name: Download bg_config.bgi into NETLOGON bginfo
      ansible.windows.win_get_url:
        url: "https://www.dropbox.com/scl/fi/oi5s2ztn3kmhvyjb84n20/bg_config.bgi?rlkey=kjxoykquz24rl9ihmkat02vvk&st=6ax9knl1&dl=1"
        dest: "{{ bginfo_dir }}\\bg_config.bgi"
        force: yes

    - name: Download wallpaper.jpg into NETLOGON bginfo
      ansible.windows.win_get_url:
        url: "https://www.dropbox.com/scl/fi/0rvz3bbo4f8tufr0i91fs/wallpaper.jpg?rlkey=kjxoykquz24rl9ihmkat02vvk&st=6ax9kszj&dl=1"
        dest: "{{ bginfo_dir }}\\wallpaper.jpg"
        force: yes

    - name: Download apply_bgi.bat into NETLOGON bginfo
      ansible.windows.win_get_url:
        url: "https://www.dropbox.com/scl/fi/8x12ka1y5epf3gt6zrjsx/apply_bgi.bat?rlkey=kjxoykquz24rl9ihmkat02vvk&st=6ax9kthq&dl=1"
        dest: "{{ bginfo_dir }}\\apply_bgi.bat"
        force: yes

    - name: Create or get GPO named "User Logon BGInfo"
      ansible.windows.win_shell: |
        $gpoName = "User Logon BGInfo"
        Import-Module GroupPolicy
        $gpo = Get-GPO -Name $gpoName -ErrorAction SilentlyContinue
        if (-not $gpo) {
          $gpo = New-GPO -Name $gpoName
        }
        Write-Output $gpo.Id
      register: gpo_guid_raw

    - name: Set GPO GUID fact
      set_fact:
        gpo_guid: "{{ gpo_guid_raw.stdout }}"

    - name: Create User Scripts Logon folder in GPO and copy apply_bgi.bat
      ansible.windows.win_shell: |
        $domain = "{{ domain_dns }}"
        $gpoGuid = "{{ gpo_guid }}"
        $gpoPath = Join-Path -Path "C:\Windows\SYSVOL\sysvol" -ChildPath $domain
        $polPath = Join-Path $gpoPath ("Policies\$gpoGuid")
        $logonFolder = Join-Path $polPath "User\Scripts\Logon"

        try {
          if (-not (Test-Path $logonFolder)) {
            New-Item -Path $logonFolder -ItemType Directory -Force | Out-Null
          }

          $sourceFile = Join-Path "{{ bginfo_dir }}" "apply_bgi.bat"
          Copy-Item -Path $sourceFile -Destination (Join-Path $logonFolder "apply_bgi.bat") -Force

          # Create scripts.ini for User Logon script using here-string
          $scriptsIni = Join-Path $logonFolder "scripts.ini"
          $content = @"
[Logon]
0CmdLine=apply_bgi.bat
0Parameters=
0ScriptDescription=Run BGInfo apply script
"@
          $content | Out-File -FilePath $scriptsIni -Encoding ASCII -Force

          Write-Output "User Logon script deployed and scripts.ini created at $scriptsIni"
        } catch {
          Write-Error "Error in GPO scripts setup: $_"
          exit 1
        }
      args:
        executable: powershell.exe
