---
- name: Deploy BGInfo files and configure GPO for all users
  hosts: srv-work
  gather_facts: yes
  collections:
    - community.windows

  tasks:
    - name: Ensure NETLOGON bginfo folder exists
      win_file:
        path: C:\Windows\SYSVOL\sysvol\work.local\scripts\bginfo
        state: directory

    - name: Download BGInfo.exe into NETLOGON bginfo folder
      win_get_url:
        url: "https://www.dropbox.com/scl/fi/7di71bkr96osmuuy54sxl/Bginfo.exe?rlkey=kjxoykquz24rl9ihmkat02vvk&st=6ax9kmr3&dl=1"
        dest: C:\Windows\SYSVOL\sysvol\work.local\scripts\bginfo\BGInfo.exe
        validate_certs: no

    - name: Download bg_config.bgi into NETLOGON bginfo folder
      win_get_url:
        url: "https://www.dropbox.com/scl/fi/h8h62xqklzq3i7h7rtpdk/bg_config.bgi?rlkey=kjxoykquz24rl9ihmkat02vvk&st=6ax8qsjr&dl=1"
        dest: C:\Windows\SYSVOL\sysvol\work.local\scripts\bginfo\bg_config.bgi
        validate_certs: no

    - name: Download wallpaper.jpg into NETLOGON bginfo folder
      win_get_url:
        url: "https://www.dropbox.com/scl/fi/5g6jh7gyn85h5mbqajk7q/wallpaper.jpg?rlkey=kjxoykquz24rl9ihmkat02vvk&st=6ax9l5y8&dl=1"
        dest: C:\Windows\SYSVOL\sysvol\work.local\scripts\bginfo\wallpaper.jpg
        validate_certs: no

    - name: Download apply_bgi.bat into NETLOGON bginfo folder
      win_get_url:
        url: "https://www.dropbox.com/scl/fi/0xlbt2zdyz7x9cu9lwmmq/apply_bgi.bat?rlkey=kjxoykquz24rl9ihmkat02vvk&st=6ax9mxkk&dl=1"
        dest: C:\Windows\SYSVOL\sysvol\work.local\scripts\bginfo\apply_bgi.bat
        validate_certs: no

    - name: Create GPO named 'BGInfo'
      community.windows.win_gpo:
        name: "BGInfo"
        state: present
      become: yes

    - name: Link 'BGInfo' GPO to the domain root
      community.windows.win_gpo_link:
        name: "BGInfo"
        state: present
        ou: "DC=work,DC=local"
      become: yes

    - name: Configure logon script in 'BGInfo' GPO
      win_shell: |
        Import-Module GroupPolicy

        $GpoName = "BGInfo"
        $ScriptName = "apply_bgi.bat"
        $ScriptPath = "\\work.local\scripts\bginfo"

        Set-GPLogonScript -Name $GpoName -ScriptName $ScriptName -ScriptPath $ScriptPath
      become: yes

    - name: Verify if GPO 'BGInfo' exists
      win_shell: |
        Import-Module GroupPolicy
        if (Get-GPO -Name "BGInfo" -ErrorAction SilentlyContinue) {
          Write-Output "GPO 'BGInfo' exists"
        } else {
          Write-Output "GPO 'BGInfo' does NOT exist"
        }
      register: gpo_check

    - debug:
        var: gpo_check.stdout
