---
- name: Deploy BGInfo files and configure User Logon GPO (srv-work only)
  hosts: windows_servers
  gather_facts: yes
  tasks:
    - name: Ensure NETLOGON bginfo folder exists
      win_file:
        path: C:\Windows\SYSVOL\sysvol\work.local\scripts\bginfo
        state: directory

    - name: Download BGInfo.exe into NETLOGON bginfo folder
      win_get_url:
        url: "https://www.dropbox.com/scl/fi/7di71bkr96osmuuy54sxl/Bginfo.exe?rlkey=kjxoykquz24rl9ihmkat02vvk&st=6ax9kmr3&dl=1"
        dest: C:\Windows\SYSVOL\sysvol\work.local\scripts\bginfo\BGInfo.exe
        validate_certs: no

    - name: Download bg_config.bgi into NETLOGON bginfo folder
      win_get_url:
        url: "https://raw.githubusercontent.com/thaper0007/cyberbud/main/playbooks/windows/files/bg_config.bgi"
        dest: C:\Windows\SYSVOL\sysvol\work.local\scripts\bginfo\bg_config.bgi
        validate_certs: no

    - name: Download wallpaper.jpg into NETLOGON bginfo folder
      win_get_url:
        url: "https://raw.githubusercontent.com/thaper0007/cyberbud/main/playbooks/windows/files/wallpaper.jpg"
        dest: C:\Windows\SYSVOL\sysvol\work.local\scripts\bginfo\wallpaper.jpg
        validate_certs: no

    - name: Download apply_bgi.bat into NETLOGON bginfo folder
      win_get_url:
        url: "https://raw.githubusercontent.com/thaper0007/cyberbud/main/playbooks/windows/files/apply_bgi.bat"
        dest: C:\Windows\SYSVOL\sysvol\work.local\scripts\bginfo\apply_bgi.bat
        validate_certs: no

    - name: Create or get GPO named 'User Logon BGInfo' and set User Logon Script
      win_shell: |
        Import-Module GroupPolicy

        $GpoName = "User Logon BGInfo"
        $gpo = Get-GPO -Name $GpoName -ErrorAction SilentlyContinue
        if (-not $gpo) {
          $gpo = New-GPO -Name $GpoName
        }

        # Set the logon script path (UNC)
        $scriptPath = "\\work.local\scripts\bginfo\apply_bgi.bat"

        # Remove existing logon scripts to avoid duplicates
        $existingScripts = Get-GPLogonScript -Name $GpoName -ErrorAction SilentlyContinue
        if ($existingScripts) {
          Remove-GPLogonScript -Name $GpoName -ScriptName $scriptPath -ErrorAction SilentlyContinue
        }

        # Add new logon script
        Set-GPLogonScript -Name $GpoName -ScriptPath $scriptPath
      args:
        executable: powershell.exe
