---
- name: Deploy BGInfo files to NETLOGON and create User Logon GPO (srv-work only)
  hosts: srv-work
  gather_facts: no
  vars:
    domain_dns: "work.local"
    bginfo_dir: "C:\\Windows\\SYSVOL\\sysvol\\{{ domain_dns }}\\bginfo"
    bginfo_url: "https://www.dropbox.com/scl/fi/7di71bkr96osmuuy54sxl/Bginfo.exe?rlkey=kjxoykquz24rl9ihmkat02vvk&st=6ax9kmr3&dl=1"
    bg_config_url: "https://www.dropbox.com/scl/fi/7ebcio36fvr1zrci8dvwk/bg_config.bgi?rlkey=8nljr7cg7gpdguc1ckmnqjg9r&st=hib8pf9i&dl=1"
    wallpaper_url: "https://www.dropbox.com/scl/fi/n2y8fx1r2m95zciwpuutk/wallpaper.jpg?rlkey=7zuuqyfsmgwin05xvjkyzaaq2&st=l1lservo&dl=1"
    apply_bat_url: "https://www.dropbox.com/scl/fi/7ebcio36fvr1zrci8dvwk/apply_bgi.bat?rlkey=8nljr7cg7gpdguc1ckmnqjg9r&st=hhkprurr&dl=1"
    gpo_name: "BGInfo User Logon"
  tasks:

    - name: Ensure NETLOGON bginfo folder exists
      ansible.windows.win_file:
        path: "{{ bginfo_dir }}"
        state: directory

    - name: Download BGInfo.exe into NETLOGON bginfo
      ansible.windows.win_get_url:
        url: "{{ bginfo_url }}"
        dest: "{{ bginfo_dir }}\\BGInfo.exe"
        force: yes
        validate_certs: no

    - name: Download bg_config.bgi into NETLOGON bginfo
      ansible.windows.win_get_url:
        url: "{{ bg_config_url }}"
        dest: "{{ bginfo_dir }}\\bg_config.bgi"
        force: yes
        validate_certs: no

    - name: Download wallpaper.jpg into NETLOGON bginfo
      ansible.windows.win_get_url:
        url: "{{ wallpaper_url }}"
        dest: "{{ bginfo_dir }}\\wallpaper.jpg"
        force: yes
        validate_certs: no

    - name: Download apply_bgi.bat into NETLOGON bginfo
      ansible.windows.win_get_url:
        url: "{{ apply_bat_url }}"
        dest: "{{ bginfo_dir }}\\apply_bgi.bat"
        force: yes
        validate_certs: no

    # Optional: create GPO and configure user startup script pointing to apply_bgi.bat in NETLOGON
    # (This requires ActiveDirectory and GroupPolicy modules on the host and rights to create GPOs)
    - name: Create or get GPO named {{ gpo_name }}
      ansible.windows.win_shell: |
        Import-Module GroupPolicy
        $gpo = Get-GPO -Name "{{ gpo_name }}" -ErrorAction SilentlyContinue
        if (-not $gpo) {
          $gpo = New-GPO -Name "{{ gpo_name }}"
        }
        Write-Output $gpo.Id.Guid
      args:
        executable: powershell.exe
      register: gpo_guid

    - name: Set GPO GUID fact
      set_fact:
        gpo_guid: "{{ gpo_guid.stdout }}"

    - name: Create user startup scripts folder and copy apply_bgi.bat
      ansible.windows.win_shell: |
        $gpoPath = "C:\Windows\SYSVOL\sysvol\{{ domain_dns }}\Policies\{{$env:GPO_GUID}}"
        $scriptsPath = Join-Path $gpoPath "User\Scripts\Logon"
        if (-not (Test-Path $scriptsPath)) {
          New-Item -Path $scriptsPath -ItemType Directory -Force | Out-Null
        }
        Copy-Item -Path "{{ bginfo_dir }}\apply_bgi.bat" -Destination (Join-Path $scriptsPath "apply_bgi.bat") -Force

        $scriptsIni = Join-Path $scriptsPath "scripts.ini"
        $content = @(
          "[Logon]"
          "0CmdLine=apply_bgi.bat"
          "0Parameters="
          "0ScriptDescription=Run BGInfo Apply Script"
        )
        $content | Out-File -FilePath $scriptsIni -Encoding ASCII -Force
      args:
        executable: powershell.exe
      environment:
        GPO_GUID: "{{ gpo_guid }}"

    - name: Link GPO to domain
      ansible.windows.win_shell: |
        Import-Module GroupPolicy
        $domainDN = (Get-ADDomain).DistinguishedName
        New-GPLink -Name "{{ gpo_name }}" -Target $domainDN -LinkEnabled Yes -ErrorAction SilentlyContinue
      args:
        executable: powershell.exe

