---
- name: Deploy BGInfo files to NETLOGON and create User Logon GPO
  hosts: windows_servers
  gather_facts: no
  vars:
    bginfo_url:    "https://www.dropbox.com/scl/fi/7di71bkr96osmuuy54sxl/Bginfo.exe?rlkey=kjxoykquz24rl9ihmkat02vvk&st=6ax9kmr3&dl=1"
    bg_config_url: "https://www.dropbox.com/scl/fi/7ebcio36fvr1zrci8dvwk/bg_config.bgi?rlkey=8nljr7cg7gpdguc1ckmnqjg9r&st=hib8pf9i&dl=1"
    wallpaper_url: "https://www.dropbox.com/scl/fi/n2y8fx1r2m95zciwpuutk/wallpaper.jpg?rlkey=7zuuqyfsmgwin05xvjkyzaaq2&st=l1lservo&dl=1"
    apply_bat_url: "https://www.dropbox.com/scl/fi/7ebcio36fvr1zrci8dvwk/bg_config.bgi?rlkey=8nljr7cg7gpdguc1ckmnqjg9r&st=hhkprurr&dl=1"

    bginfo_dir_name: "bginfo"
    gpo_name: "BGInfo - User Logon"
    gpo_link_target: ""  # empty = domain root

  tasks:
    - name: Get AD domain info
      ansible.windows.win_shell: |
        Import-Module ActiveDirectory
        $domainDns = (Get-ADDomain).DNSRoot
        $domainDN  = (Get-ADDomain).DistinguishedName
        Write-Output "$domainDns|$domainDN"
      args:
        executable: powershell.exe
      register: domain_info

    - name: Set facts from domain info
      set_fact:
        domain_dns: "{{ domain_info.stdout.split('|')[0] }}"
        domain_dn:  "{{ domain_info.stdout.split('|')[1] }}"

    - name: Ensure NETLOGON BGInfo folder exists
      ansible.windows.win_file:
        path: "C:\\Windows\\SYSVOL\\sysvol\\{{ domain_dns }}\\{{ bginfo_dir_name }}"
        state: directory

    - name: Download BGInfo.exe
      ansible.windows.win_get_url:
        url: "{{ bginfo_url }}"
        dest: "C:\\Windows\\SYSVOL\\sysvol\\{{ domain_dns }}\\{{ bginfo_dir_name }}\\BGInfo.exe"
        force: yes
        validate_certs: no

    - name: Download bg_config.bgi
      ansible.windows.win_get_url:
        url: "{{ bg_config_url }}"
        dest: "C:\\Windows\\SYSVOL\\sysvol\\{{ domain_dns }}\\{{ bginfo_dir_name }}\\bg_config.bgi"
        force: yes
        validate_certs: no

    - name: Download wallpaper.jpg
      ansible.windows.win_get_url:
        url: "{{ wallpaper_url }}"
        dest: "C:\\Windows\\SYSVOL\\sysvol\\{{ domain_dns }}\\{{ bginfo_dir_name }}\\wallpaper.jpg"
        force: yes
        validate_certs: no

    - name: Download apply_bgi.bat
      ansible.windows.win_get_url:
        url: "{{ apply_bat_url }}"
        dest: "C:\\Windows\\SYSVOL\\sysvol\\{{ domain_dns }}\\{{ bginfo_dir_name }}\\apply_bgi.bat"
        force: yes
        validate_certs: no

    - name: Create or get GPO for User Logon
      ansible.windows.win_shell: |
        Import-Module GroupPolicy
        $gpo = Get-GPO -Name "{{ gpo_name }}" -ErrorAction SilentlyContinue
        if (-not $gpo) { $gpo = New-GPO -Name "{{ gpo_name }}" }
        Write-Output $gpo.Id.Guid
      args:
        executable: powershell.exe
      register: gpo_guid_result

    - name: Set GPO GUID fact
      set_fact:
        gpo_guid: "{{ gpo_guid_result.stdout }}"

    - name: Configure GPO User Logon Script to run apply_bgi.bat from NETLOGON
      ansible.windows.win_shell: |
        Import-Module GroupPolicy
        $gpo = Get-GPO -Name "{{ gpo_name }}"
        # Set User Logon script path relative to NETLOGON
        Set-GPRegistryValue -Name "{{ gpo_name }}" -Key "HKCU\Software\Policies\Microsoft\Windows\System\Scripts\Logon" -ValueName "0CmdLine" -Type String -Value "\\{{ domain_dns }}\NETLOGON\{{ bginfo_dir_name }}\apply_bgi.bat"
        # This ensures that the script is stored as a UNC path in GPO
        Write-Output "User logon script configured."
      args:
        executable: powershell.exe

    - name: Link the GPO to domain or OU
      ansible.windows.win_shell: |
        Import-Module GroupPolicy
        $target = "{{ gpo_link_target }}"
        if ([string]::IsNullOrWhiteSpace($target)) {
          $target = (Get-ADDomain).DistinguishedName
        }
        New-GPLink -Name "{{ gpo_name }}" -Target $target -LinkEnabled Yes -Enforced No -ErrorAction SilentlyContinue
        Write-Output "GPO linked to $target"
      args:
        executable: powershell.exe
