---
- name: Deploy BGInfo files to NETLOGON and create User Logon GPO (run on srv-work only)
  hosts: srv-work
  gather_facts: no
  vars:
    # Hardcode your domain info here:
    domain_dns: "work.local"          # Change to your real domain DNS name
    domain_dn: "DC=work,DC=local"    # Change to your real domain DN

    # URLs for BGInfo files (dropbox direct download)
    bginfo_url:    "https://www.dropbox.com/scl/fi/7di71bkr96osmuuy54sxl/Bginfo.exe?rlkey=kjxoykquz24rl9ihmkat02vvk&st=6ax9kmr3&dl=1"
    bg_config_url: "https://www.dropbox.com/scl/fi/7ebcio36fvr1zrci8dvwk/bg_config.bgi?rlkey=8nljr7cg7gpdguc1ckmnqjg9r&st=hib8pf9i&dl=1"
    wallpaper_url: "https://www.dropbox.com/scl/fi/n2y8fx1r2m95zciwpuutk/wallpaper.jpg?rlkey=7zuuqyfsmgwin05xvjkyzaaq2&st=l1lservo&dl=1"
    apply_bat_url: "https://www.dropbox.com/scl/fi/7ebcio36fvr1zrci8dvwk/bg_config.bgi?rlkey=8nljr7cg7gpdguc1ckmnqjg9r&st=hhkprurr&dl=1"

    bginfo_dir_name: "bginfo"
    gpo_name: "BGInfo"
    gpo_link_target: "{{ domain_dn }}"   # Link to domain root, or set to OU DN if you want

  tasks:
    - name: Ensure NETLOGON bginfo folder exists
      ansible.windows.win_file:
        path: "C:\\Windows\\SYSVOL\\sysvol\\{{ domain_dns }}\\{{ bginfo_dir_name }}"
        state: directory

    - name: Download BGInfo.exe into NETLOGON bginfo
      ansible.windows.win_get_url:
        url: "{{ bginfo_url }}"
        dest: "C:\\Windows\\SYSVOL\\sysvol\\{{ domain_dns }}\\{{ bginfo_dir_name }}\\BGInfo.exe"
        force: yes
        validate_certs: no

    - name: Download bg_config.bgi into NETLOGON bginfo
      ansible.windows.win_get_url:
        url: "{{ bg_config_url }}"
        dest: "C:\\Windows\\SYSVOL\\sysvol\\{{ domain_dns }}\\{{ bginfo_dir_name }}\\bg_config.bgi"
        force: yes
        validate_certs: no

    - name: Download wallpaper.jpg into NETLOGON bginfo
      ansible.windows.win_get_url:
        url: "{{ wallpaper_url }}"
        dest: "C:\\Windows\\SYSVOL\\sysvol\\{{ domain_dns }}\\{{ bginfo_dir_name }}\\wallpaper.jpg"
        force: yes
        validate_certs: no

    - name: Download apply_bgi.bat into NETLOGON bginfo
      ansible.windows.win_get_url:
        url: "{{ apply_bat_url }}"
        dest: "C:\\Windows\\SYSVOL\\sysvol\\{{ domain_dns }}\\{{ bginfo_dir_name }}\\apply_bgi.bat"
        force: yes
        validate_certs: no

    - name: Create or get GPO named {{ gpo_name }}
      ansible.windows.win_shell: |
        Import-Module GroupPolicy
        $gpo = Get-GPO -Name "{{ gpo_name }}" -ErrorAction SilentlyContinue
        if (-not $gpo) {
          $gpo = New-GPO -Name "{{ gpo_name }}"
        }
        Write-Output $gpo.Id.Guid
      args:
        executable: powershell.exe
      register: gpo_guid_result

    - name: Set GPO GUID fact
      set_fact:
        gpo_guid: "{{ gpo_guid_result.stdout }}"

    - name: Create GPO User Scripts Startup folder and copy startup script
      ansible.windows.win_shell: |
        $domain = "{{ domain_dns }}"
        $gpoGuid = "{{ gpo_guid }}"
        $gpoPath = Join-Path -Path "C:\Windows\SYSVOL\sysvol" -ChildPath $domain
        $polPath = Join-Path $gpoPath ("Policies\{{$gpoGuid}}")
        $startupFolder = Join-Path $polPath "User\Scripts\Startup"

        if (-not (Test-Path $startupFolder)) {
          New-Item -Path $startupFolder -ItemType Directory -Force | Out-Null
        }

        # Copy apply_bgi.bat from NETLOGON to GPO User Scripts Startup folder
        $sourceFile = Join-Path $gpoPath "{{ bginfo_dir_name }}\apply_bgi.bat"
        Copy-Item -Path $sourceFile -Destination (Join-Path $startupFolder "apply_bgi.bat") -Force

        # Copy BGInfo files also to this folder
        Copy-Item -Path (Join-Path $gpoPath "{{ bginfo_dir_name }}\BGInfo.exe") -Destination (Join-Path $startupFolder "BGInfo.exe") -Force
        Copy-Item -Path (Join-Path $gpoPath "{{ bginfo_dir_name }}\bg_config.bgi") -Destination (Join-Path $startupFolder "bg_config.bgi") -Force
        Copy-Item -Path (Join-Path $gpoPath "{{ bginfo_dir_name }}\wallpaper.jpg") -Destination (Join-Path $startupFolder "wallpaper.jpg") -Force

        # Create scripts.ini to register the startup script
        $scriptsIni = Join-Path $startupFolder "scripts.ini"
        $content = @(
          "[Startup]"
          "0CmdLine=apply_bgi.bat"
          "0Parameters="
          "0ScriptDescription=Run BGInfo apply script"
        )
        $content | Out-File -FilePath $scriptsIni -Encoding ASCII -Force

        Write-Output "User Startup script configured at $startupFolder"
      args:
        executable: powershell.exe
      register: gpo_script_setup

    - name: Link the GPO to domain or target OU
      ansible.windows.win_shell: |
        Import-Module GroupPolicy
        $gpoName = "{{ gpo_name }}"
        $linkTarget = "{{ gpo_link_target }}"
        if ([string]::IsNullOrWhiteSpace($linkTarget)) {
          $linkTarget = (Get-ADDomain).DistinguishedName
        }
        $existingLinks = Get-GPLink -Domain (Get-ADDomain).DNSRoot | Where-Object { $_.DisplayName -eq $gpoName -and $_.Target -eq $linkTarget }
        if (-not $existingLinks) {
          New-GPLink -Name $gpoName -Target $linkTarget -LinkEnabled Yes -Enforced No
          Write-Output "GPO linked to $linkTarget"
        } else {
          Write-Output "GPO already linked to $linkTarget"
        }
      args:
        executable: powershell.exe
      register: link_result

    - name: Show summary
      ansible.builtin.debug:
        msg:
          - "Domain DNS: {{ domain_dns }}"
          - "Domain DN: {{ domain_dn }}"
          - "GPO GUID: {{ gpo_guid }}"
          - "{{ gpo_script_setup.stdout }}"
          - "{{ link_result.stdout }}"
