---
- name: Check and generate inactive users report on DCs
  hosts:
    - srv-home
    - srv-work
  gather_facts: yes
  tasks:

    - name: Ensure Reports folder exists
      ansible.windows.win_file:
        path: C:\Reports
        state: directory

    - name: Check PowerShell version
      ansible.windows.win_shell: |
        $PSVersionTable.PSVersion
      register: ps_version

    - name: Show PowerShell version
      ansible.builtin.debug:
        msg: "{{ ps_version.stdout }}"

    - name: List installed PowerShell modules
      ansible.windows.win_shell: |
        Get-Module -ListAvailable | Select-Object Name,Version | Format-Table -AutoSize
      register: modules_list

    - name: Show installed modules
      ansible.builtin.debug:
        msg: "{{ modules_list.stdout }}"

    - name: Generate inactive users report CSV on DC
      ansible.windows.win_shell: |
        $daysInactive = 7
        $dateLimit = (Get-Date).AddDays(-$daysInactive)
        Import-Module "C:\Windows\System32\WindowsPowerShell\v1.0\Modules\ActiveDirectory\ActiveDirectory.psd1"
        $inactiveUsers = Get-ADUser -Filter {LastLogonDate -lt $dateLimit -and Enabled -eq $true} -Properties LastLogonDate |
                         Select-Object Name, SamAccountName, LastLogonDate
        if ($inactiveUsers.Count -eq 0) {
          Write-Output "No inactive users found or attribute LastLogonDate missing" | Out-File "C:\Reports\InactiveUsers_$(Get-Date -Format yyyy-MM-dd).txt"
        } else {
          $inactiveUsers | Export-Csv -Path "C:\Reports\InactiveUsers_$(Get-Date -Format yyyy-MM-dd).csv" -NoTypeInformation
        }
      args:
        executable: powershell.exe
