- name: Generate inactive users report CSV on DC (with debug)
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Create Reports folder if missing
      ansible.windows.win_shell: |
        if (-not (Test-Path "C:\\Reports")) {
          New-Item -Path "C:\\Reports" -ItemType Directory | Out-Null
        }
      args:
        executable: powershell.exe

    - name: Check if ActiveDirectory module is available
      ansible.windows.win_shell: |
        try {
          Import-Module ActiveDirectory -ErrorAction Stop
          Write-Output "ModuleLoaded"
        } catch {
          Write-Output "ModuleNotLoaded: $_"
          exit 1
        }
      args:
        executable: powershell.exe
      register: ad_module_check
      failed_when: "'ModuleNotLoaded' in ad_module_check.stdout"

    - name: Generate inactive users report CSV on DC
      ansible.windows.win_shell: |
        $daysInactive = 90
        $dateLimit = (Get-Date).AddDays(-$daysInactive)
        Import-Module ActiveDirectory
        $inactiveUsers = Get-ADUser -Filter {LastLogonDate -lt $dateLimit -and Enabled -eq $true} -Properties LastLogonDate |
                         Select-Object Name, SamAccountName, LastLogonDate
        if ($inactiveUsers.Count -eq 0) {
          "No inactive users found or attribute LastLogonDate missing" | Out-File "C:\\Reports\\InactiveUsers_$(Get-Date -Format yyyy-MM-dd).txt"
        } else {
          $inactiveUsers | Export-Csv -Path "C:\\Reports\\InactiveUsers_$(Get-Date -Format yyyy-MM-dd).csv" -NoTypeInformation
        }
      args:
        executable: powershell.exe
      register: generate_report

    - name: Show generate report output
      debug:
        var: generate_report.stdout_lines
