---
- name: Generate inactive users report on Domain Controllers
  hosts: windows_servers
  gather_facts: yes
  tasks:
    - name: Create Reports folder if missing
      win_file:
        path: C:\Reports
        state: directory

    - name: Check if ActiveDirectory module is available
      win_shell: |
        if (Get-Module -ListAvailable -Name ActiveDirectory) { Write-Output "Found" } else { Write-Output "NotFound" }
      register: ad_module_check

    - name: Fail if ActiveDirectory module not found
      fail:
        msg: "ActiveDirectory PowerShell module is not available on the host."
      when: ad_module_check.stdout != "Found"

    - name: Generate inactive users report CSV on DC
      win_shell: |
        $daysInactive = 2
        $dateLimit = (Get-Date).AddDays(-$daysInactive)
        Import-Module ActiveDirectory
        $inactiveUsers = Get-ADUser -Filter {LastLogonDate -lt $dateLimit -and Enabled -eq $true} -Properties LastLogonDate |
                         Select-Object Name, SamAccountName, LastLogonDate
        $reportPath = "C:\Reports\InactiveUsers_$(Get-Date -Format yyyy-MM-dd).csv"
        $notePath = "C:\Reports\InactiveUsers_$(Get-Date -Format yyyy-MM-dd).txt"

        if ($inactiveUsers.Count -eq 0) {
          "No inactive users found or attribute LastLogonDate missing" | Out-File $notePath -Encoding UTF8
        }
        else {
          $inactiveUsers | Export-Csv -Path $reportPath -NoTypeInformation -Encoding UTF8
        }
      args:
        executable: powershell.exe
