---
- name: Run Windows Updates on DCs
  hosts: windows_servers
  tasks:
    - name: Install Windows Updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: true
