---
- name: Update Domain Controllers (Win Server 2019+)
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tasks:

    - name: Force Windows Update scan
      ansible.windows.win_shell: |
        UsoClient StartScan
      register: scan_result

    - name: Install Windows Updates (Security, Critical, Update Rollups)
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
      register: update_result

    - name: Show installed updates during this run
      debug:
        msg: "{{ update_result.updates | map(attribute='title') | list }}"

    - name: Wait for reboot to finish (if rebooted)
      ansible.windows.win_reboot:
        reboot_timeout: 600
      when: update_result.reboot_required

    - name: Confirm latest installed updates on the system
      ansible.windows.win_shell: |
        Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 10 | Format-Table -AutoSize
      register: hotfixes

    - name: Display recent installed updates on server
      debug:
        var: hotfixes.stdout_lines
